/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanalat;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;


import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author User
 */
public class inputpeminjam extends javax.swing.JFrame {

    /**
     * Creates new form inputpeminjam
     */
    public inputpeminjam() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPinput1 = new javax.swing.JPanel();
        jPinputpeminjaman = new javax.swing.JPanel();
        jLidpeminjaman = new javax.swing.JLabel();
        jLnama = new javax.swing.JLabel();
        jLalatdipinjam = new javax.swing.JLabel();
        jTFidpeminjam = new javax.swing.JTextField();
        jTFalatdipinjam = new javax.swing.JTextField();
        jTFnamapeminjam = new javax.swing.JTextField();
        jBtambahpeminjaman = new javax.swing.JButton();
        jBeditpeminjaman = new javax.swing.JButton();
        jLtglpeminjaman = new javax.swing.JLabel();
        jTFtglpeminjaman = new javax.swing.JTextField();
        jLtglpengembalian = new javax.swing.JLabel();
        jTFtglpengembalian = new javax.swing.JTextField();
        jLstatus = new javax.swing.JLabel();
        jTFstatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPdatapeminjaman = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablepeminjam = new javax.swing.JTable();
        jBdatapeminjamm = new javax.swing.JButton();
        jBcaripeminjaman = new javax.swing.JButton();
        jTFcari = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPinput1.setBackground(new java.awt.Color(57, 62, 70));

        jPinputpeminjaman.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Peminjaman", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(238, 238, 238))); // NOI18N
        jPinputpeminjaman.setOpaque(false);

        jLidpeminjaman.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLidpeminjaman.setForeground(new java.awt.Color(242, 242, 242));
        jLidpeminjaman.setText("ID Peminjam");

        jLnama.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLnama.setForeground(new java.awt.Color(242, 242, 242));
        jLnama.setText("Nama Siswa");

        jLalatdipinjam.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLalatdipinjam.setForeground(new java.awt.Color(242, 242, 242));
        jLalatdipinjam.setText("Alat dipinjam");

        jTFidpeminjam.setBackground(new java.awt.Color(0, 173, 181));
        jTFidpeminjam.setForeground(new java.awt.Color(255, 255, 255));

        jTFalatdipinjam.setBackground(new java.awt.Color(0, 173, 181));
        jTFalatdipinjam.setForeground(new java.awt.Color(255, 255, 255));

        jTFnamapeminjam.setBackground(new java.awt.Color(0, 173, 181));
        jTFnamapeminjam.setForeground(new java.awt.Color(255, 255, 255));

        jBtambahpeminjaman.setText("Tambah");
        jBtambahpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtambahpeminjamanActionPerformed(evt);
            }
        });

        jBeditpeminjaman.setText("Edit");
        jBeditpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditpeminjamanActionPerformed(evt);
            }
        });

        jLtglpeminjaman.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLtglpeminjaman.setForeground(new java.awt.Color(242, 242, 242));
        jLtglpeminjaman.setText("Tanggal Peminjaman");

        jTFtglpeminjaman.setBackground(new java.awt.Color(0, 173, 181));
        jTFtglpeminjaman.setForeground(new java.awt.Color(255, 255, 255));

        jLtglpengembalian.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLtglpengembalian.setForeground(new java.awt.Color(242, 242, 242));
        jLtglpengembalian.setText("Tanggal Pengembalian");

        jTFtglpengembalian.setBackground(new java.awt.Color(0, 173, 181));
        jTFtglpengembalian.setForeground(new java.awt.Color(255, 255, 255));

        jLstatus.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLstatus.setForeground(new java.awt.Color(242, 242, 242));
        jLstatus.setText("Status");

        jTFstatus.setBackground(new java.awt.Color(0, 173, 181));
        jTFstatus.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPinputpeminjamanLayout = new javax.swing.GroupLayout(jPinputpeminjaman);
        jPinputpeminjaman.setLayout(jPinputpeminjamanLayout);
        jPinputpeminjamanLayout.setHorizontalGroup(
            jPinputpeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPinputpeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPinputpeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLnama)
                    .addComponent(jLalatdipinjam)
                    .addComponent(jLidpeminjaman)
                    .addComponent(jLtglpeminjaman)
                    .addComponent(jLstatus)
                    .addComponent(jTFtglpengembalian)
                    .addComponent(jTFtglpeminjaman)
                    .addComponent(jLtglpengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFstatus)
                    .addComponent(jTFalatdipinjam)
                    .addComponent(jTFnamapeminjam)
                    .addComponent(jTFidpeminjam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPinputpeminjamanLayout.createSequentialGroup()
                .addGroup(jPinputpeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPinputpeminjamanLayout.createSequentialGroup()
                        .addComponent(jBtambahpeminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBeditpeminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPinputpeminjamanLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBeditpeminjaman, jBtambahpeminjaman, jButton1, jButton2});

        jPinputpeminjamanLayout.setVerticalGroup(
            jPinputpeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPinputpeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLidpeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFidpeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnamapeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLalatdipinjam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFalatdipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLtglpeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFtglpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLtglpengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFtglpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPinputpeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtambahpeminjaman)
                    .addComponent(jBeditpeminjaman)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPinputpeminjamanLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBeditpeminjaman, jBtambahpeminjaman, jButton1, jButton2});

        jPdatapeminjaman.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Peminjaman", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(238, 238, 238))); // NOI18N
        jPdatapeminjaman.setOpaque(false);

        jTablepeminjam.setBackground(new java.awt.Color(0, 173, 181));
        jTablepeminjam.setForeground(new java.awt.Color(238, 238, 238));
        jTablepeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Peminjam", "Nama_Siswa", "Alat_Dipinjam", "Tanggal_Peminjaman", "Tanggal_Pengembalian", "Status_Pengembalian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablepeminjam);
        if (jTablepeminjam.getColumnModel().getColumnCount() > 0) {
            jTablepeminjam.getColumnModel().getColumn(0).setResizable(false);
            jTablepeminjam.getColumnModel().getColumn(1).setResizable(false);
            jTablepeminjam.getColumnModel().getColumn(2).setResizable(false);
            jTablepeminjam.getColumnModel().getColumn(3).setResizable(false);
            jTablepeminjam.getColumnModel().getColumn(4).setResizable(false);
            jTablepeminjam.getColumnModel().getColumn(5).setResizable(false);
        }

        jBdatapeminjamm.setText("Data");
        jBdatapeminjamm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdatapeminjammActionPerformed(evt);
            }
        });

        jBcaripeminjaman.setText("Cari");
        jBcaripeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcaripeminjamanActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak Barcode");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPdatapeminjamanLayout = new javax.swing.GroupLayout(jPdatapeminjaman);
        jPdatapeminjaman.setLayout(jPdatapeminjamanLayout);
        jPdatapeminjamanLayout.setHorizontalGroup(
            jPdatapeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatapeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPdatapeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPdatapeminjamanLayout.createSequentialGroup()
                        .addComponent(jTFcari, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBcaripeminjaman)
                        .addGap(21, 21, 21)
                        .addComponent(jBdatapeminjamm)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 257, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPdatapeminjamanLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBcaripeminjaman, jBdatapeminjamm, jButton4});

        jPdatapeminjamanLayout.setVerticalGroup(
            jPdatapeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdatapeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPdatapeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBdatapeminjamm)
                    .addComponent(jBcaripeminjaman)
                    .addComponent(jTFcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPdatapeminjamanLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBcaripeminjaman, jBdatapeminjamm, jButton4});

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPinput1Layout = new javax.swing.GroupLayout(jPinput1);
        jPinput1.setLayout(jPinput1Layout);
        jPinput1Layout.setHorizontalGroup(
            jPinput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPinput1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPinput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPinput1Layout.createSequentialGroup()
                        .addComponent(jPinputpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPdatapeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPinput1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(19, 19, 19))))
        );
        jPinput1Layout.setVerticalGroup(
            jPinput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPinput1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPinput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPinputpeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPdatapeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPinput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPinput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBdatapeminjammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdatapeminjammActionPerformed
        // TODO add your handling code here:
        try {
        jTablepeminjam.setModel(new DefaultTableModel());
        DefaultTableModel model =(DefaultTableModel)jTablepeminjam.getModel();
        Connection conn = (Connection) dbkoneksi.getConnection();
        Statement st = conn.createStatement();
        String query="SELECT ID_Peminjam AS Id, Nama_Peminjam AS Nama, Alat_Dipinjam AS Alat, Tanggal_Peminjaman AS peminjaman,"
                + "Tanggal_Pengembalian AS pengembalian, Status_Pengembalian AS Status FROM peminjamanalat ORDER BY ID_Peminjam";
        ResultSet rs =st.executeQuery(query);
        ResultSetMetaData rsmd=(ResultSetMetaData) rs.getMetaData();
        
        int cols =rsmd.getColumnCount();
        String[] colName=new String[cols];
        for(int i=0;i<cols;i++)
            colName[i]=rsmd.getColumnName(i+1);
        model.setColumnIdentifiers(colName);
        String Id,Nama,Alat,Peminjaman,Pengembalian,Status;
        while (rs.next()){
            Id=rs.getString(1);
            Nama=rs.getString(2);
            Alat=rs.getString(3);
            Peminjaman=rs.getString(4);
            Pengembalian=rs.getString(5);
            Status=rs.getString(6);
            String[] row={Id,Nama,Alat,Peminjaman,Pengembalian,Status};
            model.addRow(row);
        }
        st.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jBdatapeminjammActionPerformed

    private void jBtambahpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtambahpeminjamanActionPerformed
        // TODO add your handling code here:
String id = jTFidpeminjam.getText();
String nama = jTFnamapeminjam.getText();
String alat = jTFalatdipinjam.getText();
String peminjaman = jTFtglpeminjaman.getText();
String pengembalian = jTFtglpengembalian.getText();
String status = jTFstatus.getText();

if (id.isEmpty() ||  nama.isEmpty() || alat.isEmpty() || peminjaman.isEmpty() 
        || pengembalian.isEmpty() || status.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Harap isi semua kolom", "Coba lagi", JOptionPane.ERROR_MESSAGE);
} else {
    try {
        DefaultTableModel model = (DefaultTableModel) jTablepeminjam.getModel();
        model.addRow(new Object[]{id, nama, alat, peminjaman, pengembalian, status});

        jTFidpeminjam.setText("");
        jTFnamapeminjam.setText("");
        jTFalatdipinjam.setText("");
        jTFtglpeminjaman.setText("");
        jTFtglpengembalian.setText("");
        jTFstatus.setText("");

        Connection k = dbkoneksi.getConnection();
        Statement s = k.createStatement();
        String q = "INSERT INTO peminjamanalat "
                 + "(ID_Peminjam, Nama_Peminjam, Alat_Dipinjam, Tanggal_Peminjaman, Tanggal_Pengembalian, Status_Pengembalian) "
                 + "VALUES ('" + id + "','" + nama + "','" + alat + "','" + peminjaman + "','"
                + pengembalian + "','" + status + "')";
        s.executeUpdate(q);
        System.out.println("Data berhasil disimpan ke database!");
    } catch (SQLException e) {
        System.err.println("Error: " + e.getMessage());
    }
}
    }//GEN-LAST:event_jBtambahpeminjamanActionPerformed

    private void jBeditpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditpeminjamanActionPerformed
        // TODO add your handling code here:
int row = jTablepeminjam.getSelectedRow();

    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Pilih salah satu data!", "Coba lagi!", JOptionPane.ERROR_MESSAGE);
    } else {
        DefaultTableModel model = (DefaultTableModel) jTablepeminjam.getModel();
        int kodeToUpdate = Integer.parseInt(model.getValueAt(row, 0).toString()); // Ambil nilai kode alat dari baris yang dipilih

        String ID_Peminjam = jTFidpeminjam.getText();
String Nama_Peminjam = jTFnamapeminjam.getText();
String Alat_Dipinjam = jTFalatdipinjam.getText();
String Tanggal_Peminjaman = jTFtglpeminjaman.getText();
String Tanggal_Pengembalian = jTFtglpengembalian.getText();
String Status_Pengembalian = jTFstatus.getText();

        // Jika tidak ada data yang dipilih untuk diubah
        if (ID_Peminjam.isEmpty() || Nama_Peminjam.isEmpty() || Alat_Dipinjam.isEmpty() || Tanggal_Peminjaman.isEmpty() || Tanggal_Pengembalian.isEmpty() || Status_Pengembalian.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua kolom", "Coba lagi", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // Hapus baris yang ada
                model.removeRow(row);

                // Tambahkan baris yang diperbarui
                model.insertRow(row, new Object[]{ID_Peminjam, Nama_Peminjam, Alat_Dipinjam, Tanggal_Peminjaman, Tanggal_Pengembalian, Status_Pengembalian});

                Connection k = dbkoneksi.getConnection();
                Statement s = k.createStatement();
                String q = "UPDATE peminjamanalat SET ID_Peminjam='" + ID_Peminjam + "', Nama_Peminjam='" + Nama_Peminjam + "', Alat_Dipinjam='" + Alat_Dipinjam + "', Tanggal_Peminjaman='" + Tanggal_Peminjaman + "', Tanggal_Pengembalian='" + Tanggal_Pengembalian + "', Status_Pengembalian='" + Status_Pengembalian +"' WHERE ID_Peminjam=" + kodeToUpdate;
                s.executeUpdate(q);
                System.out.println("Data berhasil diperbarui di database!");
            } catch (SQLException e) {
                System.err.println("Error: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_jBeditpeminjamanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = jTablepeminjam.getSelectedRow();
    
    if (row < 0) {
        JOptionPane.showMessageDialog(this,"Pilih salah satu data!", "Coba lagi!", JOptionPane.ERROR_MESSAGE);
    } else {
        DefaultTableModel model = (DefaultTableModel) jTablepeminjam.getModel();
        int kodeToDelete = Integer.parseInt(model.getValueAt(row, 0).toString()); 
        model.removeRow(row);
        
        try {
            Connection k = dbkoneksi.getConnection();
            Statement s = k.createStatement();
            String q = "DELETE FROM peminjamanalat WHERE ID_Peminjam=" + kodeToDelete; 
            s.executeUpdate(q);
            System.out.println("Data berhasil dihapus dari database!");
        } catch (SQLException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTFidpeminjam.setText("");
        jTFnamapeminjam.setText("");
        jTFalatdipinjam.setText("");
        jTFtglpeminjaman.setText("");
        jTFtglpengembalian.setText("");
        jTFstatus.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBcaripeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcaripeminjamanActionPerformed
         // TODO add your handling code here:
DefaultTableModel model = (DefaultTableModel) jTablepeminjam.getModel();
model.setRowCount(0); // Menghapus semua baris yang ada di tabel

try {
    String searchTerm = jTFcari.getText();
    Connection conn = dbkoneksi.getConnection();
    Statement stmt = conn.createStatement();
    String query = "SELECT * FROM peminjamanalat WHERE ID_Peminjam LIKE '%" + searchTerm + "%'";
    ResultSet rs = stmt.executeQuery(query);

    while (rs.next()) {
        Object[] row = {
            rs.getInt("ID_Peminjam"),
            rs.getString("Nama_Peminjam"),
            rs.getString("Alat_Dipinjam"),
            rs.getString("Tanggal_Peminjaman"),
            rs.getString("Tanggal_Pengembalian"),
            rs.getString("Status_Pengembalian")
        };
        model.addRow(row);
    }

    rs.close();
    stmt.close();
    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
}

// Menampilkan hasil pencarian di tabel
jTablepeminjam.setModel(model);

    }//GEN-LAST:event_jBcaripeminjamanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTablepeminjam.getSelectedRow();
if (selectedRow != -1) {
    String id = String.valueOf(jTablepeminjam.getValueAt(selectedRow, 0)); // Ganti indeks kolom sesuai dengan kolom yang berisi ID

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi ID terlebih dahulu", "Coba lagi", JOptionPane.ERROR_MESSAGE);
    } else {
        String data = id;
        String directory = "D:\\barcodes";
        String path = directory + "\\" + id + ".png";
        String charset = "UTF-8";
        Map<EncodeHintType, ErrorCorrectionLevel> hashMap = new HashMap<>();

        hashMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);

        try {
            BitMatrix matrix = new MultiFormatWriter().encode(
                    new String(data.getBytes(charset), charset),
                    BarcodeFormat.QR_CODE, 200, 200);

            MatrixToImageWriter.writeToFile(
                    matrix,
                    path.substring(path.lastIndexOf('.') + 1),
                    new File(path));
            System.out.println("Barcode berhasil dibuat di: " + path);
        } catch (WriterException | IOException e) {
            e.printStackTrace();
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu", "Coba lagi", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputpeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputpeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputpeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputpeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputpeminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcaripeminjaman;
    private javax.swing.JButton jBdatapeminjamm;
    private javax.swing.JButton jBeditpeminjaman;
    private javax.swing.JButton jBtambahpeminjaman;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLalatdipinjam;
    private javax.swing.JLabel jLidpeminjaman;
    private javax.swing.JLabel jLnama;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JLabel jLtglpeminjaman;
    private javax.swing.JLabel jLtglpengembalian;
    private javax.swing.JPanel jPdatapeminjaman;
    private javax.swing.JPanel jPinput1;
    private javax.swing.JPanel jPinputpeminjaman;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFalatdipinjam;
    private javax.swing.JTextField jTFcari;
    private javax.swing.JTextField jTFidpeminjam;
    private javax.swing.JTextField jTFnamapeminjam;
    private javax.swing.JTextField jTFstatus;
    private javax.swing.JTextField jTFtglpeminjaman;
    private javax.swing.JTextField jTFtglpengembalian;
    private javax.swing.JTable jTablepeminjam;
    // End of variables declaration//GEN-END:variables
}
