/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peminjamanalat;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class Riwayat extends javax.swing.JFrame {

    /**
     * Creates new form Riwayat
     */
    public Riwayat() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTFcaririwayat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 245, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Riwayat Pengembalian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(23, 107, 135))); // NOI18N
        jPanel2.setOpaque(false);

        jTFcaririwayat.setBackground(new java.awt.Color(180, 212, 255));
        jTFcaririwayat.setForeground(new java.awt.Color(23, 107, 135));
        jTFcaririwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcaririwayatActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(180, 212, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Peminjam", "Nama_Peminjam", "Alat_Dipinjam", "Tanggal_Peminjaman", "Tanggal_Pengembalian", "Status_Pengembalian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFcaririwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTFcaririwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTFcaririwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcaririwayatActionPerformed
        // TODO add your handling code here:
      String id = jTFcaririwayat.getText();
    try {
        String q = "SELECT * FROM peminjamanalat WHERE ID_Peminjam=" + id;
        Connection k = dbkoneksi.getConnection();
        Statement s = k.createStatement();
        ResultSet R = s.executeQuery(q);

        while (R.next()) {
            String ID_Peminjam = R.getString("ID_Peminjam"); // Misalkan id diambil dari kolom 'id'
            String Nama_Peminjam = R.getString("Nama_Peminjam");
            String Alat_Dipinjam = R.getString("Alat_Dipinjam");
            String Tanggal_Peminjaman = R.getString("Tanggal_Peminjaman");
            String Tanggal_Pengembalian = R.getString("Tanggal_Pengembalian");
            String Status_Pengembalian = R.getString("Status_Pengembalian");
            // Ambil kolom-kolom lain yang diperlukan dari tabel

            // Pastikan method 'updateDB' dan 'addDataToTable' didefinisikan dengan benar
            updateDB(ID_Peminjam); // Mungkin Anda ingin menyertakan ID_Peminjaman
            addDataToTable(ID_Peminjam, Nama_Peminjam, Alat_Dipinjam, Tanggal_Peminjaman, Tanggal_Pengembalian,
                    Status_Pengembalian); // Sesuaikan dengan kolom-kolom yang diperlukan
        }

        jTFcaririwayat.setText("");
        jTFcaririwayat.requestFocus();

        // Pastikan untuk menutup koneksi dan statement setelah digunakan
        R.close();
        s.close();
        k.close();
    } catch (SQLException e) {
        // Tindakan jika terjadi kesalahan
        e.printStackTrace(); // Ini akan mencetak informasi kesalahan, yang membantu dalam penanganan masalah
    }
    }//GEN-LAST:event_jTFcaririwayatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFcaririwayat;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
private void updateDB(String id) {
        try {
            Connection c = dbkoneksi.getConnection();
            Statement s = c.createStatement();
            String q = "UPDATE peminjamanalat "
                    + "SET "
                    + "Status_Pengembalian='Sudah Dikembalikan' "
                    + "WHERE ID_Peminjam="+id;
            s.executeUpdate(q);
        } catch (Exception e) {
        }
    }

    private void addDataToTable(String ID_Peminjam, String Nama_Peminjam, String Alat_Dipinjam, String Tanggal_Peminjaman, String Tanggal_Pengembalian, String Status_Pengembalian) {
        try {
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getRowCount()+1;
            Object[] dataPengembalian = {row,ID_Peminjam,Nama_Peminjam,Nama_Peminjam,Alat_Dipinjam,Tanggal_Peminjaman,Tanggal_Pengembalian,Status_Pengembalian,"Sudah Dikembalikan"};
            m.addRow(dataPengembalian); 
        } catch (Exception e) {
        }
    
    }
}


